"""Initial migration

Revision ID: ddf1831d16c1
Revises: 
Create Date: 2025-04-16 08:45:33.538389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf1831d16c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_lunches',
    sa.Column('lunch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('lunch_id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('card_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id')
    )
    op.create_table('given_lunches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lunch_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lunch_id'], ['available_lunches.lunch_id'], name='fk_given_lunch_lunch_id'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_given_lunch_student_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('today_lunch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lunch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lunch_id'], ['available_lunches.lunch_id'], name='fk_today_lunch_lunch_id'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_today_lunch_student_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('today_lunch')
    op.drop_table('given_lunches')
    op.drop_table('students')
    op.drop_table('available_lunches')
    # ### end Alembic commands ###
